eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_SERVER_HOST:localhost}:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true