server:
  port: 8764

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/matchxapp/api/products/**
          filters:
            - StripPrefix=2
        - id: matcher
          uri: lb://matching-service
          predicates:
            - Path=/matchxapp/api/match-supplier/**
          filters:
            - StripPrefix=2
        - id: supplier
          uri: lb://supplier-service
          predicates:
            - Path=/matchxapp/api/suppliers/**
          filters:
            - StripPrefix=2
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/matchxapp/api/orders/**
          filters:
            - StripPrefix=2
        - id: user
          uri: lb://auth-service
          predicates:
            - Path=/matchxapp/api/users/**
          filters:
            - StripPrefix=2
        - id: registry
          uri: lb://registry-service
          predicates:
            - Path=/matchxapp/api/registry/**
          filters:
            - StripPrefix=2
        - id: admin
          uri: lb://admin-service
          predicates:
            - Path=/matchxapp/api/admin/**
          filters:
            - StripPrefix=2
        - id: websocket
          uri: lb://notification-service
          predicates:
            - Path=/ws/**
            - Header=Connection, Upgrade
            - Header=Upgrade, websocket

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'