spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_service_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
server:
  port: 9097
logging:
  level:
    root: INFO
    com.capstone.matchxapp: DEBUG
  file.name: application.log
