spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
server:
  port: 9094
logging:
  level:
    root: INFO
    com.capstone.matchxapp: DEBUG
  file.name: application.log