spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/supplier-service-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
server:
  port: 9095
logging:
  level:
    root: INFO
    com.capstone.matchxapp: DEBUG
  file.name: application.log